name: Go

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build ./...

  check-format:
    name: Check Formatting
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'
      - name: Check formatting
        run: |
          unformatted=$(gofmt -l .)
          if [ -n "$unformatted" ]; then
            echo "Unformatted files detected:"
            echo "$unformatted"
            exit 1
          fi

  test:
    name: Run Tests on Go ${{ matrix.go-version }}
    runs-on: ubuntu-latest
    needs: check-format
    strategy:
      matrix:
        go-version: ['1.19', '1.20', '1.21.x']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Test the project
        run: go test ./... -v
